version: '3'
services:
  referenceapp:
    image: "${ASHERAH_REFERENCEAPP_IMAGE}"
    environment:
      ASHERAH_SERVICE_NAME: myapp
      ASHERAH_PRODUCT_NAME: asherah-examples
      ASHERAH_EXPIRE_AFTER: 60m
      ASHERAH_CHECK_INTERVAL: 10m
      ASHERAH_KMS_MODE: static
      ASHERAH_METASTORE_MODE: memory
    command: ["--partitions", "24"]
    ulimits:
      memlock:
        soft: -1
        hard: -1
    logging:
      driver: awslogs
      options:
        awslogs-group: asherah-samples
        awslogs-region: us-west-2
        awslogs-stream-prefix: csharp-refapp
